### ISSUE TITLE
Suggestion: content-script Support for using vue

### ISSUE THREAD

**Issue by guowenfh** [antfu/vitesse-webext#10]
Currently for `Content Script` Using`"build:js": "tsup src/background src/content --format iife --out-dir extension/dist --no-splitting"` does not support inserting vue components in the page. I think many people have such a scene. Do you think is a good idea?

**Comment by antfu** [comment]
Sorry I am not sure if I understand your use case. Can you provide some examples?

**Comment by guowenfh** [comment]
![image](https://user-images.githubusercontent.com/15883471/128664161-54c9c6d7-e58a-4552-9f0b-3494037b3a14.png)
![image](https://user-images.githubusercontent.com/15883471/128664176-1df4864f-21af-4c84-8d53-5273e34dd704.png)

Examples include the translation plugin and the github directory tree plugin, Both require some script to be inserted into the content of the page, and I want this part to support vue components
https://github.com/ineo6/git-master/
https://saladict.crimx.com/

**Comment by antfu** [comment]
I see. I think we could use Vite lib mode to do that. PR welcome.

**Comment by wensonsmith** [comment]
Same here 

When insert customer element to origin web , this feature is useful.

EG:

![image](https://user-images.githubusercontent.com/2544185/129002496-2879eae3-cdab-4877-ac73-3563ea100a30.png)

**Comment by wensonsmith** [comment]
content/index.js

```
import { createApp } from 'vue'
import Hello from './Hello.vue'

createApp(Hello).mount('#app')

```

An error has occurred， i don't know how to solve it 😢 

![image](https://user-images.githubusercontent.com/2544185/129006142-85837528-c1f9-42f8-9ad9-92f066991029.png)

**Comment by tshemeng** [comment]
@antfu @guowenfh @wensonsmith I created a PR #17. It add Vue.js support to content_script.
