### ISSUE TITLE
After pnpm install, it reports an error 

### ISSUE THREAD

**Issue by king-open** [antfu/vitesse-webext#101]
### Describe the bug

``` bash 
 ERR_STREAM_PREMATURE_CLOSE  Premature close

Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (internal/errors.js:322:7)
    at IncomingMessage.onclose (internal/streams/end-of-stream.js:117:38)
    at IncomingMessage.emit (events.js:400:28)
    at TLSSocket.socketCloseListener (_http_client.js:432:11)
    at TLSSocket.emit (events.js:412:35)
    at net.js:686:12
    at TCP.done (_tls_wrap.js:564:7)
```

### Reproduction

null 

### System Info

```Shell
MacOS 
Chrome 
`pnpm install`
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tmkx** [comment]
try to replace npm registry with  https://npmmirror.com/

**Comment by king-open** [comment]
I'll try

**Comment by king-open** [comment]
But using npm install is so slow

**Comment by king-open** [comment]
Okay, thanks.

**Comment by king-open** [comment]
Solved, thanks

**Comment by tmkx** [comment]
You can add this to your project `.npmrc` file, npm/pnpm will use it for this project:
```
registry = https://registry.npmmirror.com
```

**Comment by king-open** [comment]
My default mirror is this one
