### ISSUE TITLE
branch: refactor/mv3 use tsx

### ISSUE THREAD

**Issue by xlzy520** [antfu/vitesse-webext#112]
### Describe the bug

<img width="157" alt="image" src="https://user-images.githubusercontent.com/28336270/209798150-208df56e-2353-46a6-9419-fb531e0cbc03.png">
<img width="770" alt="image" src="https://user-images.githubusercontent.com/28336270/209798215-1b78aa3a-7224-40aa-af76-829ad3e00609.png">
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/28336270/209798241-a21ddb36-9b16-4f04-b31f-ce89828e86c3.png">

### Reproduction

file path：`vitesse-webext/src/popup/Popup.vue`

 update script lang
```js
<script setup lang="tsx">
import { storageDemo } from '~/logic/storage'

function openOptionsPage() {
  browser.runtime.openOptionsPage()
}
</script>
```

### System Info

```Shell
System:
    OS: macOS 11.7.1
    CPU: (8) arm64 Apple M1
    Memory: 103.06 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Edge: 103.0.1264.71
    Firefox: 106.0
    Safari: 14.1.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xlzy520** [comment]
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/28336270/209798815-17d62220-10d9-490f-ad21-d0183d99e38b.png">

**Comment by xlzy520** [comment]
我先用h函数进行处理jsx绕过了

**Comment by tmkx** [comment]
the `main` branch should have solve this issue. you can reopen it if not, thanks! :)
