### ISSUE TITLE
Vite server did not start

### ISSUE THREAD

**Issue by FlynnCao** [antfu/vitesse-webext#129]
### Describe the bug

I've tried both branches's code by running `pnpm install` and `pnpm run dev` directly 
and none of them work perfectly, my problems are:

I'm tryting to develop a chrome extension: 

##  `main` branch:
After running "pnpm run dev", terminal showed: 
```
[Error: ENOENT: no such file or directory, open 'E:\ChromeExtensionRepositories\antfu-templates\vitesse-webext\src\background\index.html'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\ChromeExtensionRepositories\\antfu-templates\\vitesse-webext\\src\\background\\index.html'
}
```

## `refactor/mv3` branch:
Everything worked fine during build process but after loading the extension and enable it, both the option page and popup page showed "Vite server did not start", tho it's obvious the vite server had started successfully on default port.

Really appreciate if anyone can solve my problems!

### Reproduction

None. It's from scratch.

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10600KF CPU @ 4.10GHz
    Memory: 7.87 GB / 23.85 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by betteralong** [comment]
I have the same problem.
running pnpm dev
error message
[Error: ENOENT: no such file or directory, open '/Users/yeguo/work/vitesse-webext/src/background/index.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/yeguo/work/vitesse-webext/src/background/index.html'
}

**Comment by kai2128** [comment]
The `background/index.html` has been deleted in #127 by adding index.html into the background folder should fix the problem

**Comment by tmkx** [comment]
> refactor/mv3 branch:

@FlynnCao The [latest commit](https://github.com/antfu/vitesse-webext/commit/0061436fa5f6e745aa5d3ecf48305330c9106d9d) has fixed the issue.

by the way, we recommend using pnpm, you can install dependencies by `npm i -g pnpm && pnpm i`

**Comment by FlynnCao** [comment]
> > refactor/mv3 branch:
> 
> @FlynnCao The [latest commit](https://github.com/antfu/vitesse-webext/commit/0061436fa5f6e745aa5d3ecf48305330c9106d9d) has fixed the issue.
> 
> by the way, we recommend using pnpm, you can install dependencies by `npm i -g pnpm && pnpm i`

Tks! Helps a lot~
