### ISSUE TITLE
React port of Vitesse-webext

### ISSUE THREAD

**Issue by louisremi** [antfu/vitesse-webext#140]
### Clear and concise description of the problem

Vitesse-webext is a great template for Vue lovers, and the React ecosystem deserves a similar solution.
There various efforts to port this repo to React, which can be accessed from the forks of this repo, but none of them are both up-to-date with upstream, or have feature parity

### Suggested solution

Here's my recent attempt at porting this repo to React: https://github.com/louisremi/vite-react-extension

It would be great if we cound find a solution to keep both repo relatively in sync

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thank you. But I personally have no interest in maintaining a React version, so I'd mark this as not planned.
