### ISSUE TITLE
community version that supports Manifest V3 

### ISSUE THREAD

**Issue by taricov** [antfu/vitesse-webext#143]
### Clear and concise description of the problem

Anyone found a way to upgrade from v2 to v3?

Now no one could ever benefit from this repo .. could we get it aligned w/ the new Google requirements?

![image](https://github.com/antfu/vitesse-webext/assets/65824043/8a5f949b-c40a-4761-8b9b-4895327c29db)

### Suggested solution

New branch or walk-through on how to upgrade this repo's manifest v2

### Validations

- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
We are already on V3, isn't it?
https://github.com/antfu/vitesse-webext/blob/bc8672552fd8745a2edc8b2fc6e9202c2aadf7a4/src/manifest.ts#L12

**Comment by taricov** [comment]
Thanx @antfu for the clarification, I just cloned the repo few weeks earlier and the original mainfist.ts still says 2 for the version, before I spend some time trying to upgrade and got tons of errors, solved some, but some stuck. and never had the notion to check the repos manifest again just followed the traces of some issues till despair. 

_(u could possibly headline the repo's readme with the status quo and latest/big update so folks know the change, and new cloners know where they will be on the map by using this repo ✋)_

I **will close the issue** trying things off, and will follow up if there are any unexpected scenarios 👍
