### ISSUE TITLE
Invalid assets URL in dev mode

### ISSUE THREAD

**Issue by Elliot67** [antfu/vitesse-webext#156]
### Describe the bug

In development mode, assets inside the `src/assets` folder cannot be imported from components.

## Explanation

Importing an image with `<img src="/assets/icon.svg" />` will resolve to `<img src="/assets/icon.svg" />` instead of `<img src="http://localhost:3303/assets/icon.svg" />`.
When the app is builded, the image will resolve to `/dist/assets/icon-03081ed2.svg` which works.

The provided example inside `src/options/Options.vue` currently only works because the same file exists in the `extension/assets` folder.

Note :
- The same problem also occurs with CSS import : `url('/assets/roboto.woff2')`

## Possible solutions 

- Force Vite to use a full path instead of the relative one for assets
- Use the `<base>` tag to `http://localhost:3303/` and remove it at build time

### Reproduction

Rename `src/assets/icon.svg` to something else and fix the import inside `src/options/Options.vue`

### System Info

```Shell
Windows & Chrome
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chen99-long** [comment]
I have also encountered this problem, how to solve it?

**Comment by Elliot67** [comment]
@chen99-long , I worked around the issue by adding the `<base href="http://localhost:3303/" />` tag in  the `<head>` of my options & popup html pages. Vite seems to remove the tag at build time but it can create other issues depending on your extension.

I think the proper fix should be done inside the Vite configuration directly.

**Comment by chen99-long** [comment]
Thank you very much

**Comment by sgarcia-dev** [comment]
Facing the same issue at the moment. @antfu is this a known issue?

**Comment by QC2168** [comment]
same issues
