### ISSUE TITLE
element-plus styles lose

### ISSUE THREAD

**Issue by QC2168** [antfu/vitesse-webext#163]
### Describe the bug

After importing element-plus, the component does not work properly and the style is missing

![872a0cb07cbd6f8a0e57ec1971fdc5a](https://github.com/antfu/vitesse-webext/assets/82024018/7814c4dd-ca26-4f25-97f4-6efb8c1d62f2)

### Reproduction

https://github.com/QC2168/webext-ele-import-bug

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600KF
    Memory: 9.09 GB / 31.82 GB
  Binaries:
    Node: 18.19.0 - D:\software\nodejs\node.EXE
    npm: 10.2.3 - D:\software\nodejs\npm.CMD
    pnpm: 8.15.0 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.80)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tmkx** [comment]
the css vars of element-ui are declared under the `:root` pseudo-class, this won't affect the shadow dom, one solution is to replace `:root` with `:host`:

```ts
// vite.config.content.ts
export default defineConfig({
  css: {
    postcss: {
      plugins: [
        {
          postcss(root) {
            root.walkRules((rule) => {
              if (rule.selector === ':root')
                rule.selector = ':host'
            })
          },
        },
      ],
    },
  },
})
```

**Comment by QC2168** [comment]
@tmkx thanks! It's working properly

**Comment by pnhuyduy** [comment]
@tmkx I have same issue with `Naive UI`, how to fix this?
![image](https://github.com/antfu/vitesse-webext/assets/46210597/81a8fcf9-4812-496e-aaaa-4c4e6cb9cff5)

**Comment by tmkx** [comment]
naive ui creates style tags in the `<head />`, but content-script is isolated in a shadow root.

<img width="569" alt="image" src="https://github.com/antfu/vitesse-webext/assets/13805071/9d9a79be-18d5-49d2-b401-6e2d2e70a441">

**Comment by tmkx** [comment]
naive ui relies on the [css-render](https://github.com/07akioni/css-render) library, there is a relevant PR about this issue https://github.com/07akioni/css-render/pull/1105, but it was merged 9 months ago and has NOT published a new version 🤔。

**Comment by patrikb42222** [comment]
Is it possible to use PrimeVue in the content script? The styles seem broken there too.

**Comment by patrikb42222** [comment]
I managed to get the 3.53.0 themes working by importing the css directly into the component file.
`import 'primevue/resources/themes/aura-light-green/theme.css'`
The resources have been removed as of 4.0 so I'm not sure if it's possible to upgrade

**Comment by patrikb42222** [comment]
PrimeVue >4.0 puts <style> tag inside the <head> element. I wrote a content script that moves PrimeVue styles from there to inside the shadow root.

`function movePrimeVueStyles(shadowDOM: ShadowRoot | HTMLElement) {
  // Observe if any new styles are added by PrimeVue
  observeHeadForStyles(shadowDOM)

  const headStyles = document.querySelectorAll('head > style[type="text/css"][data-primevue-style-id]')
  headStyles.forEach((styleEl) => {
    // Clone the style element to move it to the shadow DOM
    const clonedStyleEl = styleEl.cloneNode(true) as HTMLStyleElement
    shadowDOM.appendChild(clonedStyleEl)
    styleEl.remove()
  })
}
function observeHeadForStyles(shadowDOM: ShadowRoot | HTMLElement) {
  const head = document.head

  // Create a MutationObserver to watch for new <style> elements in <head>
  const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
      mutation.addedNodes.forEach((node) => {
        if (node instanceof HTMLStyleElement && node.hasAttribute('data-primevue-style-id')) {
          // Clone and move the new PrimeVue style to the shadow DOM
          const clonedStyleEl = node.cloneNode(true) as HTMLStyleElement
          shadowDOM.appendChild(clonedStyleEl)
          node.remove()
        }
      })
    })
  })

  // Observe changes to the <head> element
  observer.observe(head, { childList: true, subtree: true })
}
`
