### ISSUE TITLE
Content scripts in dev mode don't work in Firefox

### ISSUE THREAD

**Issue by caudurodev** [antfu/vitesse-webext#27]
Great work on this project! But since I mainly develop in FF I thought I would mention that there is an issue specific to FF which works fine in chromium browsers. If dev mode is enabled (HMR) the content scripts don't even load in the page. Build works fine in FF. Without ```delete manifest.content_scripts``` the development mode works, but requires the extension to be reloaded manually.

**Comment by mattrothenberg** [comment]
I'm unable to get content scripts working in dev mode in Chrome, too. 

Able to reproduce by:
1. Cloning
2. Installing dependencies
3. Running the `dev` script
4. Running `start:chromium`
5. Seeing that the content script is not being included
6. Running the `build` script
7.  Running `start:chromium`
8. Seeing that the content script IS being included

**Comment by tshemeng** [comment]
@mattrothenberg  In my test, web-ext has a delay in loading extension, if open a url at browser startup quickly(often occurs when `web-ext run` with `--start-url` command), the extension's background script is not yet executed, so contentscript is not injected. You can open the url in dev mode, wait a moment to refresh the page and see if the extension loads properly.

If the problem still exists, you can open the `chrome://extensions/` page, enable `developer mode`, and click the view ` dist/background/index.html` `console` tab to see if there is any error message.
