### ISSUE TITLE
How to serve assets?

### ISSUE THREAD

**Issue by dragoonzx** [antfu/vitesse-webext#45]
Currently I have an error: Failed to load resource: net::ERR_FILE_NOT_FOUND when trying to include image  like in this doc https://vitejs.dev/guide/assets.html

How you include assets in your extensions?

**Comment by tmkx** [comment]
for example, if your want to include images like `import imgUrl from './assets/pic.jpg'` and then set it to src, you will need to specify the base URL.

if the page is options/popup, one simple way is:
```typescript
// main.ts
import browser from 'webextension-polyfill'

const baseElem = document.createElement('base')
baseElem.href = __DEV__ ? 'http://localhost:3303' : browser.runtime.getURL('/')
document.head.appendChild(baseElem)
```
