### ISSUE TITLE
Replace Vue with React

### ISSUE THREAD

**Issue by id3vz** [antfu/vitesse-webext#5]
Thanks for this great work!
Is there any way to replace Vue with React?

**Comment by antfu** [comment]
Should be straight forward to change the two main.ts to react dom and replace vite plugin in vite.config.ts

**Comment by jacksteamdev** [comment]
Best quick solution is to disable fast refresh in the react plugin:

```javascript
// vite.config.ts
react({ fastRefresh: false })
```
