### ISSUE TITLE
Suggestion: can we have a universal extension template

### ISSUE THREAD

**Issue by nopantsmonkey** [antfu/vitesse-webext#6]
Hey Everyone,

I am suggesting if we can have a universal extension template with options to use (Plain JS, TS, Vue, React, Angular, Svelte etc) through a cli  and create a best possible webext template repo with best practices used in creating extensions for cross browser extension development.

I can help with Angular, JS, TS, Svelte templates for WebExt.

What do you all suggest? Is it a good idea?

**Comment by antfu** [comment]
Thanks for bringing this up.

However I am using Vue exclusively and I personally have no interest in maintaining other frameworks. If you want, feel free to fork it and maintaining by your own. If they work well, I am happy to have the links to them in the readme for redirection.

**Comment by dit7ya** [comment]
Hey @nopantsmonkey, are you thinking of creating other templates? It would be super useful for me if there were a Svelte one.

**Comment by nopantsmonkey** [comment]
I can create one for svelte but i am a bit busy right now so i might start it next week. Will inform you here.

Thanks
