### ISSUE TITLE
pnpm install fails

### ISSUE THREAD

**Issue by TonyThorne** [antfu/vitesse-webext#70]
I have installed the template using the following commands:

```
npx degit antfu/vitesse-webext my-webext
cd my-webext
pnpm i
```

The pnpm i fails with the following error.

```
 WARN  GET https://registry.npmjs.org/esbuild-windows-64/download/esbuild-windows-64-0.13.3.tgz error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/esbuild-windows-64/download/esbuild-windows-64-0.13.3.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
Progress: resolved 761, reused 758, downloaded 0, added 0, done
 ENOENT  ENOENT: no such file or directory, open 'C:\development\projects\vonster-webext\node_modules\.pnpm\esbuild-windows-64@0.13.3\node_modules\esbuild-windows-64\package.json'

I then tried the default Vitesse template, which worked fine.
```

**Comment by tmkx** [comment]
try `pnpm i --force` to recreate a lockfile

**Comment by tmkx** [comment]
delete pnpm-lock.yaml，and run `pnpm i`

It seems that the download url of package has broken.

**Comment by TonyThorne** [comment]
Thanks. That worked :-)
I deleted the `pnpm-lock.yaml`, and ran `pnpm i`, this had some different errors, so I ran `pnpm i --force` and it worked. :-) Thanks very much for your help.

![image](https://user-images.githubusercontent.com/6304471/157297237-1ae24b33-1822-4d03-a3b4-66a3143786c6.png)
