### ISSUE TITLE
env.ts:17 Uncaught ReferenceError: __DEFINES__ is not defined     at env.ts:17:17

### ISSUE THREAD

**Issue by martinhschei** [antfu/vitesse-webext#79]
I see that this have been a problem before, but i'm running vite 2.9.5 and still get it.

Is there a fix?

![image](https://user-images.githubusercontent.com/21332243/168776313-0ecbfe07-822c-4afa-aa43-e3b292143f8b.png)

![image](https://user-images.githubusercontent.com/21332243/168776398-df7d71a1-1a30-4f5b-8bee-709208fb6914.png)

**Comment by tmkx** [comment]
could you provide a way to reproduce it?

**Comment by tmkx** [comment]
closed for no response, reopen it if necessary
