### ISSUE TITLE
Cannot publish to store because of obfuscated code

### ISSUE THREAD

**Issue by KeziahMoselle** [antfu/vitesse-webext#8]
Hello, I'm trying to publish my extension built with this great template, however the Chrome store does not help :

![Screenshot_20210807-131222.jpg](https://user-images.githubusercontent.com/9168097/128598321-b0c8a656-fd4e-4dc5-8658-478396051a6c.jpg)

Is there any workaround ?

I'm using npm run build then zipping the extension folder

Thank you !

**Comment by tmkx** [comment]
@KeziahMoselle Did this resolved ?

**Comment by KeziahMoselle** [comment]
Unfortunately not, I deactivated minification but apparently they don't like the TS compilation @tmkx so I kinda gave up for now.

**Comment by tmkx** [comment]
https://developer.chrome.com/docs/webstore/program_policies/#:~:text=Code%20Readability%20Requirements

> Developers must not obfuscate code or conceal functionality of their extension. This also applies to any external code or resource fetched by the extension package. Minification is allowed, including the following forms:
> 
> - Removal of whitespace, newlines, code comments, and block delimiters
> - Shortening of variable and function names
> - Collapsing files together

In short, minifies is allowed while obfuscated isn't, so `vite build` shouldn't use uglify too. (The screenshot shows that *windi* violated the rule)

@antfu @KeziahMoselle
