### ISSUE TITLE
Can't Inject Vue App into the Content Script

### ISSUE THREAD

**Issue by flashclub** [antfu/vitesse-webext#91]
### Describe the bug

Hi, the contentScripts inject not work when I checkout branch to refactor/mv3. But it works when I checkout branch to main.
is anyone can help me? This question has been bothering me for a long time, thank you very much.

### Reproduction

Create a repo from this template on GitHub. Clone project. checkout branch refactor/mv3. Delete pnpm-lock.yaml file. Enter pnpm i. Enter pnpm dev

### System Info

```Shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 15.56 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 96.0
    Safari: 14.1.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ZengTianShengZ** [comment]
also doesn't work when I checkout branch to main.

**Comment by flashclub** [comment]
> also doesn't work when I checkout branch to main.

You mean inject content script doesn't work?
BTW, main branch is MV2, It's can work at Jan, 2023. So I wish default branch is MV3

**Comment by zmwangx** [comment]
See https://github.com/antfu/vitesse-webext/issues/59#issuecomment-1157626773.

**Comment by flashclub** [comment]
> 

Thanks a lot it works

**Comment by flashclub** [comment]
> See [#59 (comment)](https://github.com/antfu/vitesse-webext/issues/59#issuecomment-1157626773).

Thanks a lot it works
